### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
## 📑 Description

Fix typos found via `codespell`

## ✅ Checks

- [x] My pull request adheres to the code style of this project if any
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed if any

### CODE REVIEW

**Comment by szepeviktor** [comment]
There is one more.
https://github.com/wasi-master/pypi-command-line/blob/main/images/pypi%20browse%20alligned.gif

`images/pypi browse alligned.gif -> images/pypi browse aligned.gif`

**Comment by wasi-master** [comment]
Thanks, will publish soon!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Comment by wasi-master** [comment]
Published! https://pypi.org/project/pypi-command-line/1.7.1/

**Pull request merged**
