### PR TITLE
Fix typo in image name

### PR DESCRIPTION
**Pull request by szepeviktor**
Follow-up of #23

### CODE REVIEW

**Comment by wasi-master** [comment]
Oh didn’t see that comment sorry.

**Comment by wasi-master** [comment]
Changing this would require me to change file name too right?

**Comment by szepeviktor** [comment]
> to change file name too right?

It is included in this PR.

**Comment by wasi-master** [comment]
Oh sorry I missed that, Thanks.

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
